### ISSUE TITLE
Define appearance product chat

### ISSUE THREAD

**Issue by neuncreative** [porsche-design-system/digital-design#142]
Scope
---
Define appearance of chat button of thirt party chat service.

- consider solution that works on dark/light theme
- select icon from existing repository of thirt party supplier
- define appearance based on pds tokens

Notes
---
- Reference Links: https://www.figma.com/design/EkdP468u4ZVuIRwalKCscb/branch/ZEeQCKfSXYOjCI8yOODKKa/Web-Design-System-v3?m=auto&node-id=34934-11426&t=t9CvdTVnpySGTons-1
- Important annotations

Acceptance Criteria
---
- [ ] What has to be done to close the task

**Comment by marcelbertram** [comment]
Redundant
