### ISSUE TITLE
Provide Color Mapping for SaaS Tools (Update Brandguide)

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/digital-design#151]
Scope
---
To support SaaS Solutions in adapting the Porsche Design Language without using the code based Design System we need to provide a mapping for colors and contexts.

Notes
---
- Update Brand Guide File
- Provide concrete mapping for LeanIX, Confluence 
- Brand Guide File: https://brand.porsche.com/document/1058/en#/colors/specifications/ui-colors

Acceptance Criteria
---
- [x] Host figma file in private designsystem@porsche.de user
- [x] General color mapping added to Figma file in brandguide
- [x] Color mapping & assets for LeanIX

**Comment by marcelbertram** [comment]
![Image](https://github.com/user-attachments/assets/532d36c4-06b0-47af-86da-ef7825caaef9)
![Image](https://github.com/user-attachments/assets/f51330a8-ab73-4b2a-a486-dd32bef54c38)
![Image](https://github.com/user-attachments/assets/1ab12b0e-255e-4b90-bfcf-e30bc4200d93)
![Image](https://github.com/user-attachments/assets/2be1b7d1-7851-417a-9b0f-feea59be067f)

**Comment by muellernaumann** [comment]
done
