### ISSUE TITLE
Refine "campaign" email template in alignment with VMK/PCNA

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/digital-design#43]
Scope
---
Currently PCNA created individual e-mail templates based on an own styleguide and for future target group (Driven by dreams) not following the new design language and e-mail templates. We convinced them to follow the new CI templates. But they have specific requirements, that we have to incorporate and test.

Notes
---
- Figma Page E-Mail: https://www.figma.com/file/YGDgGPeBEzfJJjFAz0Lbzn/E-Mail-(C5)?type=design&node-id=720-10319&mode=design&t=vhvNKAWM4beBMD04-4
- Style Guide PCNA: [Porsche_Email_StyleGuide_03 (1).pdf](https://github.com/porsche-design-system/digital-design/files/12249186/Porsche_Email_StyleGuide_03.1.pdf)
- PCNA Brand Template: forward to content hub https://www.porsche.com/dreams/en-US/in-culture/ice-cream
[Q2_Brand_NEWSLETTER\[3\].pdf](https://github.com/porsche-design-system/digital-design/files/12310369/Q2_Brand_NEWSLETTER.3.pdf)
- Technical implementation must be validated with Ceterez / C5
- Individual differences compared to the VMK template must be highlighted (due to implementation efforts)
- Current US examples including visual assets can be found here: [October monthly](https://cramerkrasselt-my.sharepoint.com/personal/eebenhoch_c-k_com/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Feebenhoch%5Fc%2Dk%5Fcom%2FDocuments%2FPorsche%2FNewsletter%2F10%5FOctober%20Newsletter%2FOct%5FNewsletter%5FTobias%20Assets&ga=1) [Taycan](https://cramerkrasselt-my.sharepoint.com/personal/eebenhoch_c-k_com/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Feebenhoch%5Fc%2Dk%5Fcom%2FDocuments%2FPorsche%2FTaycan%20October%20Email%2FTaycan%5FConquest%5FTobias%20Assets&ga=1)

Acceptance Criteria
---
- [x] New Design proposals for PCNA must be compared with existing brand templates and modules, differences must be highlighted
- [x] At least on layout using the assets and content provided from PCNA to show the new design is working

**Comment by neuncreative** [comment]
Need a password for the file Figma file!
