### ISSUE TITLE
Singapur Support | Porsche Drive Rental/Abo

### ISSUE THREAD

**Issue by muellernaumann** [porsche-design-system/digital-design#59]
Scope
---
Create Designs for the Porsche Drive Flow. 
Drive Landingpage (Subscription+Rental+Testdrive)
Reference: https://porsche-drive.ae/ or https://www.porsche.com/germany/motorsportandevents/porschedrive/  
Booking Flow covering
- Subscription (Used Cars, from finder)
- Rental (New Car Fleet, specific model)
- Testdrive (Generic Derivate) 

Reference: Reservation Flow https://porsche-drive.ae/reservation or https://porscheonlinesales.com/POR/SG/finder/Z225Z2 (book a test drive)
Excluding Global Widgets: Payment/Adress/PID

Notes
---
- Figma File: https://www.figma.com/file/PnBzISaQv6dIRF6rvN5mEi/The-Singapur-Experience?type=design&node-id=78-19479&mode=design&t=pdLkLtNRds6WYbPx-0

Acceptance Criteria
---
- [ ] Screens ready for key screens and features
- [ ] Designs presented and refined with business
- [ ] Designs presented and refined with dev team

**Comment by marcelbertram** [comment]
Paused
