### ISSUE TITLE
SPIKE: Cleanup relevant icons for export and release in Design System

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/digital-design#64]
Scope
---
Currently most of the icons in V3 / One UI that have been created by ESD are not drawn with cleaned paths why the file size increases heavily compared to the existing. To replace to the new design language we want to cleanup the svgs in Figma and prepare them for export.

Notes
---
- Pick 10 Icons: Focus on icons with highest size increase & Focus on icons with highest visual change / improvement, e.g. User
- Reference Links: https://www.figma.com/file/EkdP468u4ZVuIRwalKCscb/Design-System-v3?type=design&node-id=5211-33425&mode=design&t=of7kYPQbH02gxPoN-0

Acceptance Criteria
---
- [ ] Set of 10 optimized icons is available as SVG for Figma / Code

**Comment by neuncreative** [comment]
Icons for global navigation were improved
